import { uuid } from './formbuilder/UUID';

const items_library = [
    {
        element: 'Header',
        text: 'Header Text',
        static: true,
        required: false,
        bold: false,
        italic: false,
        content: 'Placeholder text...',
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
    },
    {
        element: 'Label',
        text: 'Label',
        static: true,
        required: false,
        bold: false,
        italic: false,
        content: 'Placeholder text...',
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
    },
    {
        element: 'Paragraph',
        text: 'Paragraph',
        static: true,
        required: false,
        bold: false,
        italic: false,
        content: 'Placeholder text...',
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
    },
    {
        element: 'LineBreak',
        text: 'Line Break',
        static: true,
        required: false,
        bold: false,
        italic: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
    },
    {
        element: 'Dropdown',
        text: 'Dropdown',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'dropdown_65098C3C-0BC6-4627-83F2-F8991C606C79',
        label: 'Placeholder label',
        options: [Array],
    },
    {
        element: 'Tags',
        text: 'Tags',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'tags_F1DD3740-8A04-4A9A-9E3F-00F316114BCC',
        label: 'Placeholder label',
        options: [Array],
    },
    {
        element: 'Checkboxes',
        text: 'Checkboxes',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'checkboxes_BAD55D65-0583-44BE-A06C-AAB9719F9B00',
        label: 'Placeholder label',
        options: [Array],
    },
    {
        element: 'RadioButtons',
        text: 'Multiple Choice',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'radiobuttons_901B5A25-BDAF-4E81-9528-16E5876795D3',
        label: 'Placeholder label',
        options: [Array],
    },
    {
        element: 'TextInput',
        text: 'Text Input',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'text_input_50E895A5-4E3D-419F-95DD-98EC4B1290F1',
        label: 'Placeholder label',
    },
    {
        element: 'EmailInput',
        text: 'Email',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'email_input_C84DAF56-D150-44B0-9681-95CDEC7A73EA',
        label: 'E-Mail',
    },
    {
        element: 'NumberInput',
        text: 'Number Input',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'number_input_BA2B3019-32CF-4F71-A147-AF0A9CD44340',
        label: 'Placeholder label',
    },
    {
        element: 'PhoneNumber',
        text: 'Phone Number',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'phone_input_173783D0-4C04-4853-A9AB-9793FB3E227B',
        label: 'Phone Number',
    },
    {
        element: 'TextArea',
        text: 'Multi-line Input',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'text_area_C6AF51C1-D999-452D-9940-DAB5EBE79B1B',
        label: 'Placeholder label',
    },
    {
        element: 'FieldSet',
        text: 'Fieldset',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'fieldset-elementB5C422FA-A0DF-4E82-A012-13D034BB8282',
        label: 'Fieldset',
        childItems: [Array],
        isContainer: true,
    },
    {
        element: 'TwoColumnRow',
        text: 'Two Column Row',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'two_col_row_6AC17022-BE21-40A1-AF0B-D918977EADB3',
        childItems: [Array],
        isContainer: true,
    },
    {
        element: 'ThreeColumnRow',
        text: 'Three Columns Row',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'three_col_row_B09A4181-FFB9-4C23-B1D1-FBE9A0BED4B1',
        childItems: [Array],
        isContainer: true,
    },
    {
        element: 'MultiColumnRow',
        text: 'Four Columns Row',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        class_name: 'col-md-3',
        col_count: 4,
        field_name: 'four_col_row_1764E3DF-2CF7-4847-9D0B-7F2723903FF7',
        childItems: [Array],
        isContainer: true,
    },
    {
        element: 'MultiColumnRow',
        text: 'Five Columns Row',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        class_name: 'col',
        col_count: 5,
        field_name: 'five_col_row_9D369F8F-A60A-4A3F-9712-170488CF1259',
        childItems: [Array],
        isContainer: true,
    },
    {
        element: 'MultiColumnRow',
        text: 'Six Columns Row',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        class_name: 'col-md-2',
        col_count: 6,
        field_name: 'six_col_row_CE4F1C34-B912-4948-AD59-362A06956453',
        childItems: [Array],
        isContainer: true,
    },
    {
        element: 'Image',
        text: 'Image',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        src: '',
        field_name: 'image_211FC62F-F356-418D-A579-194B273DC083',
    },
    {
        element: 'Rating',
        text: 'Rating',
        required: false,
        canHaveAnswer: true,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'rating_06BA445B-2F02-438E-AE7C-B192E47454DC',
        label: 'Placeholder label',
    },
    {
        element: 'DatePicker',
        text: 'Date',
        required: false,
        readOnly: false,
        defaultToday: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        dateFormat: 'MM/dd/yyyy',
        timeFormat: 'hh:mm aa',
        showTimeSelect: false,
        showTimeSelectOnly: false,
        showTimeInput: false,
        field_name: 'date_picker_EE1D2AA0-6355-4357-8F8E-AE38D9BC30E9',
        label: 'Placeholder label',
    },
    {
        element: 'Signature',
        text: 'Signature',
        required: false,
        readOnly: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'signature_BCB5EA10-3184-4321-9734-231310597AD5',
        label: 'Signature',
    },
    {
        element: 'HyperLink',
        text: 'Website',
        static: true,
        required: false,
        bold: false,
        italic: false,
        content: 'Placeholder website Link...',
        href: 'http://www.example.com',
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
    },
    {
        element: 'Download',
        text: 'File Attachment',
        static: true,
        required: false,
        bold: false,
        italic: false,
        content: 'Placeholder file name...',
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        _href: '',
        file_path: '',
        field_name: 'download_8E84C7EE-B073-4B4F-B967-4FADC46FDDA0',
    },
    {
        element: 'Range',
        text: 'Range',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        step: 1,
        default_value: 3,
        min_value: 1,
        max_value: 5,
        min_label: 'Easy',
        max_label: 'Difficult',
        field_name: 'range_2FBC5BE6-6D16-4282-8DAE-088D9F2A7C5D',
        label: 'Placeholder label',
    },
    {
        element: 'Camera',
        text: 'Camera',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'camera_1670607F-0DD3-4084-9975-2560DB3470DF',
        label: 'Placeholder label',
    },
    {
        element: 'FileUpload',
        text: 'File Upload',
        required: false,
        canHavePageBreakBefore: true,
        canHaveAlternateForm: true,
        canHaveDisplayHorizontal: true,
        canHaveOptionCorrect: true,
        canHaveOptionValue: true,
        canPopulateFromApi: true,
        field_name: 'file_upload_0BCCD88B-039B-4C4F-96ED-C57C9EF048BE',
        label: 'Placeholder label',
    },
];
// .map((elm) => {
//     elm['id'] = `${uuid()}`;
//     elm['field_name'] = `${elm.element.toLowerCase()}_${uuid()}`
//     return elm;
// });

export function getItemTemplateBy(key, value, include = {}) {
    const targetItem = items_library.find(item => (item[key] ? item[key] === value : false));

    if (!targetItem) {
        return null;
    }
    return { ...targetItem, ...include } ?? null;
}

export const available_items_library = [
    {
        key: 'Header',
        name: 'header-text',
        icon: 'fas fa-heading',
        static: true,
        content: 'place-holder-text',
    },
    {
        key: 'Label',
        name: 'label',
        static: true,
        icon: 'fas fa-font',
        content: 'place-holder-text',
    },
    {
        key: 'Paragraph',
        name: 'paragraph',
        static: true,
        icon: 'fas fa-paragraph',
        content: 'place-holder-text',
    },
    {
        key: 'LineBreak',
        name: 'line-break',
        static: true,
        icon: 'fas fa-arrows-alt-h',
    },
    {
        key: 'FieldSet',
        canHaveAnswer: false,
        name: 'fieldset',
        label: 'fieldset',
        icon: 'fas fa-bars',
        field_name: 'fieldset-element',
    },
    {
        key: 'TwoColumnRow',
        canHaveAnswer: false,
        name: 'two-columns-row',
        label: '',
        icon: 'fas fa-columns',
        field_name: 'two_col_row_',
    },
    {
        key: 'ThreeColumnRow',
        canHaveAnswer: false,
        name: 'three-columns-row',
        label: '',
        icon: 'fas fa-columns',
        field_name: 'three_col_row_',
    },
    {
        key: 'FourColumnRow',
        element: 'MultiColumnRow',
        canHaveAnswer: false,
        name: 'four-columns-row',
        label: '',
        icon: 'fas fa-columns',
        field_name: 'four_col_row_',
        col_count: 4,
        class_name: 'col-md-3',
    },
    {
        key: 'FiveColumnRow',
        element: 'MultiColumnRow',
        canHaveAnswer: false,
        name: 'five-columns-row',
        label: '',
        icon: 'fas fa-columns',
        field_name: 'five_col_row_',
        col_count: 5,
        class_name: 'col',
    },
    {
        key: 'SixColumnRow',
        element: 'MultiColumnRow',
        canHaveAnswer: false,
        name: 'six-columns-row',
        label: '',
        icon: 'fas fa-columns',
        field_name: 'six_col_row_',
        col_count: 6,
        class_name: 'col-md-2',
    },
];

// console.log(items_library.map(item => item['element']));
// console.log(items_library.find(item => item['element'] == 'Header'));

// console.log(getItemTemplateBy('sdf', 'fge'));
